# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNGoogleMapsTutorial' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for RNGoogleMapsTutorial

  pod 'GoogleMaps'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'

  target 'RNGoogleMapsTutorialTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
